// 태그(#해시태그)에 한글 팀명/리그명을 같이 붙이기 위한 매핑.
// API-Football에서 오는 영문 팀명을 key로 쓴다. 목록에 없는 팀은 영문 태그만 붙는다 —
// 매핑을 계속 추가해나가면 된다(오탐보다 미포함이 안전하다).

export const LEAGUE_NAME_KO: Record<string, string> = {
  "Premier League": "프리미어리그",
  "La Liga": "라리가",
  "Bundesliga": "분데스리가",
  "Serie A": "세리에A",
  "Ligue 1": "리그1",
  "K League 1": "K리그1",
  "UEFA Champions League": "챔피언스리그",
  "Champions League": "챔피언스리그",
  "UEFA Europa League": "유로파리그",
  "Europa League": "유로파리그",
  "FA Cup": "FA컵",
}

export const TEAM_NAME_KO: Record<string, string> = {
  // Premier League
  "Arsenal": "아스날",
  "Aston Villa": "아스톤 빌라",
  "Bournemouth": "본머스",
  "Brentford": "브렌트포드",
  "Brighton": "브라이턴",
  "Burnley": "번리",
  "Chelsea": "첼시",
  "Crystal Palace": "크리스탈 팰리스",
  "Everton": "에버튼",
  "Fulham": "풀럼",
  "Leeds": "리즈 유나이티드",
  "Leeds United": "리즈 유나이티드",
  "Leicester": "레스터 시티",
  "Leicester City": "레스터 시티",
  "Liverpool": "리버풀",
  "Manchester City": "맨체스터 시티",
  "Manchester United": "맨체스터 유나이티드",
  "Newcastle": "뉴캐슬 유나이티드",
  "Newcastle United": "뉴캐슬 유나이티드",
  "Nottingham Forest": "노팅엄 포레스트",
  "Sunderland": "선덜랜드",
  "Tottenham": "토트넘 홋스퍼",
  "West Ham": "웨스트햄 유나이티드",
  "West Ham United": "웨스트햄 유나이티드",
  "Wolves": "울버햄튼",
  "Wolverhampton": "울버햄튼",
  "Ipswich": "입스위치 타운",
  "Southampton": "사우스햄튼",
  "Luton": "루턴 타운",

  // La Liga
  "Real Madrid": "레알 마드리드",
  "Barcelona": "바르셀로나",
  "Atletico Madrid": "아틀레티코 마드리드",
  "Sevilla": "세비야",
  "Real Sociedad": "레알 소시에다드",
  "Real Betis": "레알 베티스",
  "Athletic Club": "아틀레틱 빌바오",
  "Villarreal": "비야레알",
  "Valencia": "발렌시아",
  "Celta Vigo": "셀타 비고",
  "Osasuna": "오사수나",
  "Getafe": "헤타페",
  "Girona": "지로나",
  "Rayo Vallecano": "라요 바예카노",
  "Mallorca": "마요르카",
  "Las Palmas": "라스팔마스",
  "Alaves": "알라베스",
  "Espanyol": "에스파뇰",
  "Leganes": "레가네스",
  "Real Valladolid": "바야돌리드",

  // Bundesliga
  "Bayern Munich": "바이에른 뮌헨",
  "Bayern München": "바이에른 뮌헨",
  "Borussia Dortmund": "보루시아 도르트문트",
  "RB Leipzig": "RB 라이프치히",
  "Bayer Leverkusen": "바이어 레버쿠젠",
  "Union Berlin": "우니온 베를린",
  "Eintracht Frankfurt": "아인트라흐트 프랑크푸르트",
  "Wolfsburg": "볼프스부르크",
  "Borussia Monchengladbach": "보루시아 묀헨글라트바흐",
  "Borussia M'gladbach": "보루시아 묀헨글라트바흐",
  "Mainz 05": "마인츠",
  "Freiburg": "프라이부르크",
  "Hoffenheim": "호펜하임",
  "Werder Bremen": "베르더 브레멘",
  "FC Augsburg": "아우크스부르크",
  "VfB Stuttgart": "슈투트가르트",
  "FC Koln": "쾰른",
  "1. FC Köln": "쾰른",
  "VfL Bochum": "보훔",
  "Heidenheim": "하이덴하임",
  "St Pauli": "FC 장크트파울리",
  "Hamburger SV": "함부르크",
  "Holstein Kiel": "홀슈타인 킬",

  // Serie A
  "Juventus": "유벤투스",
  "Inter": "인터 밀란",
  "AC Milan": "AC 밀란",
  "Napoli": "나폴리",
  "Roma": "AS 로마",
  "Lazio": "라치오",
  "Atalanta": "아탈란타",
  "Fiorentina": "피오렌티나",
  "Bologna": "볼로냐",
  "Torino": "토리노",
  "Udinese": "우디네세",
  "Sassuolo": "사수올로",
  "Genoa": "제노아",
  "Cagliari": "칼리아리",
  "Lecce": "레체",
  "Verona": "엘라스 베로나",
  "Hellas Verona": "엘라스 베로나",
  "Parma": "파르마",
  "Como": "코모",
  "Venezia": "베네치아",
  "Empoli": "엠폴리",
  "Monza": "몬차",
  "Cremonese": "크레모네세",
  "Pisa": "피사",

  // Ligue 1
  "Paris Saint Germain": "파리 생제르맹",
  "Marseille": "마르세유",
  "Monaco": "모나코",
  "Lyon": "리옹",
  "Lille": "릴",
  "Nice": "니스",
  "Rennes": "렌",
  "Lens": "랑스",
  "Strasbourg": "스트라스부르",
  "Toulouse": "툴루즈",
  "Nantes": "낭트",
  "Montpellier": "몽펠리에",
  "Reims": "렝스",
  "Brest": "브레스트",
  "Le Havre": "르아브르",
  "Auxerre": "옥세르",
  "Angers": "앙제",
  "Metz": "메스",
  "Paris FC": "파리 FC",

  // K League 1
  "FC Seoul": "FC서울",
  "Jeonbuk Hyundai Motors": "전북 현대 모터스",
  "Jeonbuk Motors": "전북 현대 모터스",
  "Ulsan Hyundai": "울산 HD",
  "Ulsan HD": "울산 HD",
  "Pohang Steelers": "포항 스틸러스",
  "Suwon Samsung Bluewings": "수원 삼성 블루윙즈",
  "Incheon United": "인천 유나이티드",
  "Daegu FC": "대구 FC",
  "Gwangju FC": "광주 FC",
  "Gangwon FC": "강원 FC",
  "Jeju United": "제주 유나이티드",
  "Suwon FC": "수원 FC",
  "Jeonnam Dragons": "전남 드래곤즈",
  "Gimcheon Sangmu": "김천 상무",
  "Anyang": "FC 안양",
  "FC Anyang": "FC 안양",
  "Bucheon FC 1995": "부천 FC 1995",
}
